### PR TITLE
Use revised input data

### PR DESCRIPTION
**Pull request by RickMohr**
@lossyrob, running with an updated dataset my ingest failed. My changes are in this PR.

Setting up the ssh tunnel for the Spark UI failed with Permission denied (publickey) -- do I need different keys than I've been using for azavea-datahub?

``` bash
ssh -i ~/azavea-data.pem -N -D 8157 hadoop@ec2-54-88-174-245.compute-1.amazonaws.com
```

Looking through the logs (https://console.aws.amazon.com/elasticmapreduce/home?region=us-east-1#cluster-details:j-2GSBEQYQAI31Y) I saw this in the stderr of one container. Red herring? After termination and not in any other container logs:

```
16/06/10 14:26:25 INFO DAGScheduler: ResultStage 0 (reduce at TileLayerMetadata.scala:125) finished in 244.422 s
16/06/10 14:26:25 INFO YarnClusterScheduler: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/06/10 14:26:25 INFO DAGScheduler: Job 0 finished: reduce at TileLayerMetadata.scala:125, took 245.344623 s
16/06/10 14:26:25 INFO SparkUI: Stopped Spark web UI at http://172.31.24.73:41711
16/06/10 14:26:25 INFO YarnClusterSchedulerBackend: Shutting down all executors
16/06/10 14:26:25 INFO YarnClusterSchedulerBackend: Asking each executor to shut down
16/06/10 14:26:25 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
16/06/10 14:26:25 INFO MemoryStore: MemoryStore cleared
16/06/10 14:26:25 INFO BlockManager: BlockManager stopped
16/06/10 14:26:25 INFO BlockManagerMaster: BlockManagerMaster stopped
16/06/10 14:26:25 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/06/10 14:26:25 INFO SparkContext: Successfully stopped SparkContext
16/06/10 14:26:25 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
16/06/10 14:26:25 ERROR ApplicationMaster: User class threw exception: java.lang.IllegalArgumentException: requirement failed: Multiple CRS tags found: Set(geotrellis.proj4.CRS$$anon$1@9e79869, geotrellis.proj4.CRS$$anon$1@6f44e0a4)
java.lang.IllegalArgumentException: requirement failed: Multiple CRS tags found: Set(geotrellis.proj4.CRS$$anon$1@9e79869, geotrellis.proj4.CRS$$anon$1@6f44e0a4)
    at scala.Predef$.require(Predef.scala:233)
    at geotrellis.spark.TileLayerMetadata$.collectMetadataWithCRS(TileLayerMetadata.scala:136)
    at geotrellis.spark.TileLayerMetadata$.fromRdd(TileLayerMetadata.scala:172)
    at geotrellis.spark.etl.Etl.tile(Etl.scala:134)
    at treecanopy.Ingest$.main(Main.scala:50)
    at treecanopy.Ingest.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:542)
16/06/10 14:26:25 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
16/06/10 14:26:25 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.IllegalArgumentException: requirement failed: Multiple CRS tags found: Set(geotrellis.proj4.CRS$$anon$1@9e79869, geotrellis.proj4.CRS$$anon$1@6f44e0a4))
16/06/10 14:26:25 INFO ShutdownHookManager: Shutdown hook called
16/06/10 14:26:25 INFO ShutdownHookManager: Deleting directory /mnt1/yarn/usercache/hadoop/appcache/application_1465568289716_0001/spark-1158bc3c-1bc5-455e-806d-b560f9d1be00
16/06/10 14:26:25 INFO ShutdownHookManager: Deleting directory /mnt/yarn/usercache/hadoop/appcache/application_1465568289716_0001/spark-ef6cfbca-4216-43cf-aa3c-7d6054f2d4a1
```

### CODE REVIEW

**Comment by lossyrob** [comment]
Looks like the dataset contains multiple CRS's. You need to use the option

``` console
--reproject per-tile
```

to reproject per tile instead of the buffered reprojection. Hopefully this will not cause NoData seam issues. If it does we can solve that problem, just is a bit more tricky.

**Comment by RickMohr** [comment]
Thanks, I'll try it. Any suggestion for how to get the public key to enable the Spark UI for `EMR_TARGET=s3://azavea-datahub/emr/treecanopy-ingest` as opposed to `EMR_TARGET=s3://azavea-datahub/emr`

**Comment by lossyrob** [comment]
Not sure what you mean by enabling the Spark UI for a different key prefix
under the same bucket. What issue are you running up against?

**Comment by RickMohr** [comment]
The issue I mentioned at the very top -- setting up the ssh tunnel for the Spark UI failed with Permission denied (publickey). I used the .pem file that has worked for my other ingests. Do I need a different one?

``` bash
ssh -i ~/azavea-data.pem -N -D 8157 hadoop@ec2-54-88-174-245.compute-1.amazonaws.com
```

**Comment by lossyrob** [comment]
Check the key that was used in the start cluster command. It would have to
be azavea-data.pem, probably someone committed the file with an alternate
key.

**Comment by RickMohr** [comment]
`--reproject per-tile` did the trick. Interestingly it took 3.5 hours vs. 6.5 hours for the original (per @jwalgran's memory).

Ready to merge.

**Comment by jwalgran** [comment]
I make no case for that being an accurate memory ;-)

**Pull request closed without merging**
